# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.dimension_slash.locator', 'aj.dimension_slash.locator.dimension_slash_locator']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:dimension_slash/zzz/2
data modify entity @s data.locators.dimension_slash_locator.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.dimension_slash.locator', 'aj.dimension_slash.locator.player_camera']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:dimension_slash/zzz/3
data modify entity @s data.locators.player_camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.small_group10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_small_group10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.moonveil_slash] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_moonveil_slash set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.moonveil] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_moonveil set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.body_top] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.dimension_slash.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out