# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.commands.uuid
function animated_java:dimension_slash/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.dimension_slash_locator.uuid
function animated_java:dimension_slash/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.player_camera.uuid
function animated_java:dimension_slash/zzz/execute with storage aj:temp