# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.steel_caller.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:steel_caller/as_root/pre_tick
execute if entity @s[tag=aj.steel_caller.animation.steel_caller.playing] run function animated_java:steel_caller/animations/steel_caller/zzz/on_tick
execute on passengers if entity @s[tag=aj.steel_caller.data] run function animated_java:steel_caller/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:steel_caller/as_root/post_tick