# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.aquamarine_dagger.uuid
function animated_java:crystal_blade/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.player_camera.uuid
function animated_java:crystal_blade/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.commands.uuid
function animated_java:crystal_blade/zzz/execute with storage aj:temp