# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.dimension_slash.root] run return 0
execute on passengers if entity @s[tag=aj.dimension_slash.data] unless data entity @s {data:{rigHash: '17e38e9630139efee50b086fd59118e9abe64690872361d451c22cbe17a7748a'}} on vehicle run function animated_java:dimension_slash/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1