# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:crystal_blade/remove/zzz/kill with entity @s data.locators.aquamarine_dagger
function animated_java:crystal_blade/remove/zzz/kill with entity @s data.locators.player_camera