# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.crystal_blade.root] run return 0
execute on passengers if entity @s[tag=aj.crystal_blade.data] unless data entity @s {data:{rigHash: '7b8980d336a0d60ab959b064ee637bb7f3763d8aefa28319e46d74ea269e1f57'}} on vehicle run function animated_java:crystal_blade/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1