# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.crystal_blade.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:crystal_blade/as_root/pre_tick
execute if entity @s[tag=aj.crystal_blade.animation.crystal_blade.playing] run function animated_java:crystal_blade/animations/crystal_blade/zzz/on_tick
execute if entity @s[tag=aj.crystal_blade.animation.crystal_blade_heavy.playing] run function animated_java:crystal_blade/animations/crystal_blade_heavy/zzz/on_tick
execute on passengers if entity @s[tag=aj.crystal_blade.data] run function animated_java:crystal_blade/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:crystal_blade/as_root/post_tick