# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.champions_charge.frame dummy
execute as @e[type=item_display,tag=aj.champions_charge.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:champions_charge/root/on_load