# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.dimension_slash.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dimension_slash', 'function_path': 'animated_java:dimension_slash/animations/dimension_slash/stop'}
tag @s remove aj.dimension_slash.animation.dimension_slash.playing
scoreboard players set @s aj.dimension_slash.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:dimension_slash/animations/dimension_slash/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only