# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.blade_of_peril.frame dummy
execute as @e[type=item_display,tag=aj.blade_of_peril.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:blade_of_peril/root/on_load