# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.blade_of_peril.root] run return 0
execute on passengers if entity @s[tag=aj.blade_of_peril.data] unless data entity @s {data:{rigHash: 'b4738e446f51a509b95513bdec3a20705a2c062fe28226399ca23b06e081fd80'}} on vehicle run function animated_java:blade_of_peril/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1