# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.rkss_cancel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'rkss_cancel', 'function_path': 'animated_java:rkss_cancel/animations/rkss_skill/play'}
tag @s add aj.rkss_cancel.animation.rkss_skill.playing
scoreboard players set @s aj.rkss_skill.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:rkss_cancel/animations/rkss_skill/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only