# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
kill @e[tag=aj.messemers_assault.locator]
kill @e[tag=aj.kill @e[tag=aj.messemers_assault.bone]
kill @e[tag=aj.kill @e[tag=aj.messemers_assault.root,limit=1,sort=nearest]
execute as @a[limit=1,sort=nearest] run function championsashes:animated_effects/ride_off