# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.rkss_cancel.locator', 'aj.rkss_cancel.locator.rkss1']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:rkss_cancel/zzz/2
data modify entity @s data.locators.rkss1.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.rkss_cancel.locator', 'aj.rkss_cancel.locator.rkss2']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:rkss_cancel/zzz/3
data modify entity @s data.locators.rkss2.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.rkss_cancel.locator', 'aj.rkss_cancel.locator.rkss3']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:rkss_cancel/zzz/4
data modify entity @s data.locators.rkss3.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.rkss_cancel.locator', 'aj.rkss_cancel.locator.rkss4']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:rkss_cancel/zzz/5
data modify entity @s data.locators.rkss4.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.rkss_cancel.locator', 'aj.rkss_cancel.locator.rkss5']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:rkss_cancel/zzz/6
data modify entity @s data.locators.rkss5.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.rkss_cancel.locator', 'aj.rkss_cancel.locator.player_camera']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:rkss_cancel/zzz/7
data modify entity @s data.locators.player_camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.black_knight_shield] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_black_knight_shield set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.flame_slash] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame_slash set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.sword_body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_sword_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.ringed_knight_straight_sword] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ringed_knight_straight_sword set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.body_top] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.rkss_cancel.bone.flame_blast] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame_blast set from storage aj:uuid main.out