# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.rkss1.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.rkss2.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.rkss3.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.rkss4.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.rkss5.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.player_camera.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame1.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame2.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame3.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame4.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.commands.uuid
function animated_java:rkss_cancel/zzz/execute with storage aj:temp