# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.champions_charge.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'champions_charge', 'function_path': 'animated_java:champions_charge/variants/default/apply'}
execute on passengers if entity @s[tag=aj.champions_charge.bone.right_arm2] run function animated_java:champions_charge/variants/default/zzz/0
execute on passengers if entity @s[tag=aj.champions_charge.bone.right_arm] run function animated_java:champions_charge/variants/default/zzz/1
execute on passengers if entity @s[tag=aj.champions_charge.bone.steel_slash] run function animated_java:champions_charge/variants/default/zzz/2
execute on passengers if entity @s[tag=aj.champions_charge.bone.gundyr_halberd] run function animated_java:champions_charge/variants/default/zzz/3
execute on passengers if entity @s[tag=aj.champions_charge.bone.left_arm2] run function animated_java:champions_charge/variants/default/zzz/4
execute on passengers if entity @s[tag=aj.champions_charge.bone.left_arm] run function animated_java:champions_charge/variants/default/zzz/5
execute on passengers if entity @s[tag=aj.champions_charge.bone.head] run function animated_java:champions_charge/variants/default/zzz/6
execute on passengers if entity @s[tag=aj.champions_charge.bone.body_top] run function animated_java:champions_charge/variants/default/zzz/7
execute on passengers if entity @s[tag=aj.champions_charge.bone.body] run function animated_java:champions_charge/variants/default/zzz/8
execute on passengers if entity @s[tag=aj.champions_charge.bone.right_leg2] run function animated_java:champions_charge/variants/default/zzz/9
execute on passengers if entity @s[tag=aj.champions_charge.bone.right_leg] run function animated_java:champions_charge/variants/default/zzz/10
execute on passengers if entity @s[tag=aj.champions_charge.bone.left_leg2] run function animated_java:champions_charge/variants/default/zzz/11
execute on passengers if entity @s[tag=aj.champions_charge.bone.left_leg] run function animated_java:champions_charge/variants/default/zzz/12