# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:dimension_slash/remove/zzz/kill with entity @s data.locators.dimension_slash_locator
function animated_java:dimension_slash/remove/zzz/kill with entity @s data.locators.player_camera