# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.champions_charge.root] run return 0
execute on passengers if entity @s[tag=aj.champions_charge.data] unless data entity @s {data:{rigHash: 'b2265d9dfff9fbd574f162deed48a0d2bd7c897f931a8a62beca1e26c67cea37'}} on vehicle run function animated_java:champions_charge/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1