# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.champions_charge.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:champions_charge/as_root/pre_tick
execute if entity @s[tag=aj.champions_charge.animation.champions_charge.playing] run function animated_java:champions_charge/animations/champions_charge/zzz/on_tick
execute on passengers if entity @s[tag=aj.champions_charge.data] run function animated_java:champions_charge/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:champions_charge/as_root/post_tick