# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.crystal_blade.frame dummy
scoreboard objectives add aj.crystal_blade_heavy.frame dummy
execute as @e[type=item_display,tag=aj.crystal_blade.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:crystal_blade/root/on_load