# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:rkss_cancel/root/zzz/2 with entity @s data.locators.rkss1
function animated_java:rkss_cancel/root/zzz/4 with entity @s data.locators.rkss2
function animated_java:rkss_cancel/root/zzz/6 with entity @s data.locators.rkss3
function animated_java:rkss_cancel/root/zzz/8 with entity @s data.locators.rkss4
function animated_java:rkss_cancel/root/zzz/10 with entity @s data.locators.rkss5
function animated_java:rkss_cancel/root/zzz/12 with entity @s data.locators.player_camera