# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.slash1.uuid
function animated_java:champions_charge/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.gundyr_halberd1.uuid
function animated_java:champions_charge/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.gundyr_halberd2.uuid
function animated_java:champions_charge/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.gundyr_halberd3.uuid
function animated_java:champions_charge/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.player_camera.uuid
function animated_java:champions_charge/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.commands.uuid
function animated_java:champions_charge/zzz/execute with storage aj:temp