# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:champions_charge/remove/zzz/kill with entity @s data.locators.slash1
function animated_java:champions_charge/remove/zzz/kill with entity @s data.locators.gundyr_halberd1
function animated_java:champions_charge/remove/zzz/kill with entity @s data.locators.gundyr_halberd2
function animated_java:champions_charge/remove/zzz/kill with entity @s data.locators.gundyr_halberd3
function animated_java:champions_charge/remove/zzz/kill with entity @s data.locators.player_camera