# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blade_of_peril.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blade_of_peril', 'function_path': 'animated_java:blade_of_peril/animations/blade_of_peril/next_frame'}
execute if score @s aj.blade_of_peril.frame matches 79.. run scoreboard players set @s aj.blade_of_peril.frame 1
execute store result storage aj:temp frame int 1 run scoreboard players get @s aj.blade_of_peril.frame
execute at @s run function animated_java:blade_of_peril/animations/blade_of_peril/zzz/apply_frame with storage aj:temp
scoreboard players add @s aj.blade_of_peril.frame 1