# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.blade_of_peril.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'blade_of_peril', 'function_path': 'animated_java:blade_of_peril/animations/blade_of_peril/play'}
tag @s add aj.blade_of_peril.animation.blade_of_peril.playing
scoreboard players set @s aj.blade_of_peril.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:blade_of_peril/animations/blade_of_peril/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only