# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.steel_caller.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'steel_caller', 'function_path': 'animated_java:steel_caller/animations/steel_caller/stop'}
tag @s remove aj.steel_caller.animation.steel_caller.playing
scoreboard players set @s aj.steel_caller.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:steel_caller/animations/steel_caller/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only