# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.rkss_cancel.frame dummy
scoreboard objectives add aj.rkss_skill.frame dummy
execute as @e[type=item_display,tag=aj.rkss_cancel.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:rkss_cancel/root/on_load