# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rkss_cancel.root] run return 0
execute on passengers if entity @s[tag=aj.rkss_cancel.data] unless data entity @s {data:{rigHash: '6a3289c8589da10a34e561b1945ce1939a43a3f18f56f5d0f05fc58669a9e985'}} on vehicle run function animated_java:rkss_cancel/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1