# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rkss_cancel.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
function #animated_java:rkss_cancel/as_root/pre_tick
execute if entity @s[tag=aj.rkss_cancel.animation.rkss_cancel.playing] run function animated_java:rkss_cancel/animations/rkss_cancel/zzz/on_tick
execute if entity @s[tag=aj.rkss_cancel.animation.rkss_skill.playing] run function animated_java:rkss_cancel/animations/rkss_skill/zzz/on_tick
execute on passengers if entity @s[tag=aj.rkss_cancel.data] run function animated_java:rkss_cancel/root/zzz/1
execute at @s on passengers run tp @s ~ ~ ~ ~ ~
function #animated_java:rkss_cancel/as_root/post_tick