# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.player_camera.uuid
function animated_java:blade_of_peril/zzz/execute with storage aj:temp