# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if data storage aj:temp {args:{variant:''}} run return run function animated_java:blade_of_peril/zzz/4
execute store success score #success aj.i run function animated_java:blade_of_peril/zzz/5 with storage aj:temp args
execute unless score #success aj.i matches 1 run return run function animated_java:blade_of_peril/zzz/6 with storage aj:temp args