# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.rkss_cancel.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'rkss_cancel', 'function_path': 'animated_java:rkss_cancel/variants/ignite/apply'}
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.black_knight_shield] run function animated_java:rkss_cancel/variants/ignite/zzz/0
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.right_arm2] run function animated_java:rkss_cancel/variants/ignite/zzz/1
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.right_arm] run function animated_java:rkss_cancel/variants/ignite/zzz/2
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.flame_slash] run function animated_java:rkss_cancel/variants/ignite/zzz/3
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.sword_body] run function animated_java:rkss_cancel/variants/ignite/zzz/4
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.ringed_knight_straight_sword] run function animated_java:rkss_cancel/variants/ignite/zzz/5
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.left_arm2] run function animated_java:rkss_cancel/variants/ignite/zzz/6
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.left_arm] run function animated_java:rkss_cancel/variants/ignite/zzz/7
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.head] run function animated_java:rkss_cancel/variants/ignite/zzz/8
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.body_top] run function animated_java:rkss_cancel/variants/ignite/zzz/9
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.body] run function animated_java:rkss_cancel/variants/ignite/zzz/10
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.right_leg2] run function animated_java:rkss_cancel/variants/ignite/zzz/11
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.right_leg] run function animated_java:rkss_cancel/variants/ignite/zzz/12
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.left_leg2] run function animated_java:rkss_cancel/variants/ignite/zzz/13
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.left_leg] run function animated_java:rkss_cancel/variants/ignite/zzz/14
execute on passengers if entity @s[tag=aj.rkss_cancel.bone.flame_blast] run function animated_java:rkss_cancel/variants/ignite/zzz/15