# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.messemers_assault.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'messemers_assault', 'function_path': 'animated_java:messemers_assault/animations/messemers_assault/stop'}
tag @s remove aj.messemers_assault.animation.messemers_assault.playing
scoreboard players set @s aj.messemers_assault.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:messemers_assault/animations/messemers_assault/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only