# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.spear_head']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/2
data modify entity @s data.locators.spear_head.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.spear_body']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/3
data modify entity @s data.locators.spear_body.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.spear_body1']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/4
data modify entity @s data.locators.spear_body1.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.player_camera']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/5
data modify entity @s data.locators.player_camera.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.flame1']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/6
data modify entity @s data.locators.flame1.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.flame2']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/7
data modify entity @s data.locators.flame2.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.flame3']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/8
data modify entity @s data.locators.flame3.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.messemers_assault.locator', 'aj.messemers_assault.locator.flame4']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:messemers_assault/zzz/9
data modify entity @s data.locators.flame4.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.flame_slash2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame_slash2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.flame_slash] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame_slash set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.impaling_thrust] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_impaling_thrust set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_of_the_impaler] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_of_the_impaler set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.body_top] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.flame_blast] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_flame_blast set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects0] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects0 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects1] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects3] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects4] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects5] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects6] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects7] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects7 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects8] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects9] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects10] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.messemers_assault.bone.spear_effects11] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_spear_effects11 set from storage aj:uuid main.out