# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:temp uuid set from entity @s data.locators.spear_head.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body1.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.player_camera.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame1.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame2.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame3.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.flame4.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head2.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body2.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body3.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head3.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body4.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body5.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head4.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body6.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body7.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head5.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body8.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body9.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head6.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body10.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body11.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head7.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body12.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body13.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head8.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body14.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body15.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head9.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body16.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body17.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head10.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body18.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body19.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head11.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body20.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body21.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head12.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body22.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body23.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_head13.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body24.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.spear_body25.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp
data modify storage aj:temp uuid set from entity @s data.locators.commands.uuid
function animated_java:messemers_assault/zzz/execute with storage aj:temp