# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers run function animated_java:blade_of_peril/remove/zzz/kill_passengers
kill @s