# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:champions_charge/root/zzz/2 with entity @s data.locators.slash1
function animated_java:champions_charge/root/zzz/4 with entity @s data.locators.gundyr_halberd1
function animated_java:champions_charge/root/zzz/6 with entity @s data.locators.gundyr_halberd2
function animated_java:champions_charge/root/zzz/8 with entity @s data.locators.gundyr_halberd3
function animated_java:champions_charge/root/zzz/10 with entity @s data.locators.player_camera