# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.spear_head
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.spear_body
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.spear_body1
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.player_camera
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.flame1
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.flame2
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.flame3
function animated_java:messemers_assault/remove/zzz/kill with entity @s data.locators.flame4