# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:steel_caller/root/zzz/2 with entity @s data.locators.ledo_hammer
function animated_java:steel_caller/root/zzz/4 with entity @s data.locators.ledo_hammer2
function animated_java:steel_caller/root/zzz/6 with entity @s data.locators.player_camera