# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.steel_caller.locator', 'aj.steel_caller.locator.ledo_hammer']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:steel_caller/zzz/2
data modify entity @s data.locators.ledo_hammer.uuid set from storage aj:uuid main.out
summon minecraft:marker ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.steel_caller.locator', 'aj.steel_caller.locator.ledo_hammer2']}
execute as @e[type=minecraft:marker,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:steel_caller/zzz/3
data modify entity @s data.locators.ledo_hammer2.uuid set from storage aj:uuid main.out
summon minecraft:item_display ~ ~ ~ {Tags:['aj.new', 'aj.locator', 'aj.steel_caller.locator', 'aj.steel_caller.locator.player_camera']}
execute as @e[type=minecraft:item_display,tag=aj.new,tag=aj.locator,limit=1,distance=..0.01] run function animated_java:steel_caller/zzz/4
data modify entity @s data.locators.player_camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.right_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.right_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.ledo_slash] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ledo_slash set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.ledo_great_hammer] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_ledo_great_hammer set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.left_arm2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.left_arm] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_arm set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.body_top] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.right_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.right_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_right_leg set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.left_leg2] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.steel_caller.bone.left_leg] run function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.bone_left_leg set from storage aj:uuid main.out