# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.crystal_blade.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'crystal_blade', 'function_path': 'animated_java:crystal_blade/variants/ignite/apply'}
execute on passengers if entity @s[tag=aj.crystal_blade.bone.right_arm2] run function animated_java:crystal_blade/variants/ignite/zzz/0
execute on passengers if entity @s[tag=aj.crystal_blade.bone.right_arm] run function animated_java:crystal_blade/variants/ignite/zzz/1
execute on passengers if entity @s[tag=aj.crystal_blade.bone.crystal_effect] run function animated_java:crystal_blade/variants/ignite/zzz/2
execute on passengers if entity @s[tag=aj.crystal_blade.bone.crystal_slash] run function animated_java:crystal_blade/variants/ignite/zzz/3
execute on passengers if entity @s[tag=aj.crystal_blade.bone.aquamarine_dagger] run function animated_java:crystal_blade/variants/ignite/zzz/4
execute on passengers if entity @s[tag=aj.crystal_blade.bone.left_arm2] run function animated_java:crystal_blade/variants/ignite/zzz/5
execute on passengers if entity @s[tag=aj.crystal_blade.bone.left_arm] run function animated_java:crystal_blade/variants/ignite/zzz/6
execute on passengers if entity @s[tag=aj.crystal_blade.bone.head] run function animated_java:crystal_blade/variants/ignite/zzz/7
execute on passengers if entity @s[tag=aj.crystal_blade.bone.body_top] run function animated_java:crystal_blade/variants/ignite/zzz/8
execute on passengers if entity @s[tag=aj.crystal_blade.bone.body] run function animated_java:crystal_blade/variants/ignite/zzz/9
execute on passengers if entity @s[tag=aj.crystal_blade.bone.right_leg2] run function animated_java:crystal_blade/variants/ignite/zzz/10
execute on passengers if entity @s[tag=aj.crystal_blade.bone.right_leg] run function animated_java:crystal_blade/variants/ignite/zzz/11
execute on passengers if entity @s[tag=aj.crystal_blade.bone.left_leg2] run function animated_java:crystal_blade/variants/ignite/zzz/12
execute on passengers if entity @s[tag=aj.crystal_blade.bone.left_leg] run function animated_java:crystal_blade/variants/ignite/zzz/13