# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:rkss_cancel/remove/zzz/kill with entity @s data.locators.rkss1
function animated_java:rkss_cancel/remove/zzz/kill with entity @s data.locators.rkss2
function animated_java:rkss_cancel/remove/zzz/kill with entity @s data.locators.rkss3
function animated_java:rkss_cancel/remove/zzz/kill with entity @s data.locators.rkss4
function animated_java:rkss_cancel/remove/zzz/kill with entity @s data.locators.rkss5
function animated_java:rkss_cancel/remove/zzz/kill with entity @s data.locators.player_camera