# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.steel_caller.frame dummy
execute as @e[type=item_display,tag=aj.steel_caller.root] unless score @s aj.is_rig_loaded matches 1 at @s run function animated_java:steel_caller/root/on_load