# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.messemers_assault.root] run return 0
execute on passengers if entity @s[tag=aj.messemers_assault.data] unless data entity @s {data:{rigHash: '22e6b1d6ee3babb138aa21febca105fa91ad9647772442e279d7a5d8fa299bee'}} on vehicle run function animated_java:messemers_assault/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1