# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=item_display,tag=aj.dimension_slash.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'dimension_slash', 'function_path': 'animated_java:dimension_slash/variants/slash2/apply'}
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group1] run function animated_java:dimension_slash/variants/slash2/zzz/0
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group2] run function animated_java:dimension_slash/variants/slash2/zzz/1
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group3] run function animated_java:dimension_slash/variants/slash2/zzz/2
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group4] run function animated_java:dimension_slash/variants/slash2/zzz/3
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group5] run function animated_java:dimension_slash/variants/slash2/zzz/4
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group6] run function animated_java:dimension_slash/variants/slash2/zzz/5
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group7] run function animated_java:dimension_slash/variants/slash2/zzz/6
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group8] run function animated_java:dimension_slash/variants/slash2/zzz/7
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group9] run function animated_java:dimension_slash/variants/slash2/zzz/8
execute on passengers if entity @s[tag=aj.dimension_slash.bone.small_group10] run function animated_java:dimension_slash/variants/slash2/zzz/9
execute on passengers if entity @s[tag=aj.dimension_slash.bone.right_arm2] run function animated_java:dimension_slash/variants/slash2/zzz/10
execute on passengers if entity @s[tag=aj.dimension_slash.bone.right_arm] run function animated_java:dimension_slash/variants/slash2/zzz/11
execute on passengers if entity @s[tag=aj.dimension_slash.bone.left_arm2] run function animated_java:dimension_slash/variants/slash2/zzz/12
execute on passengers if entity @s[tag=aj.dimension_slash.bone.moonveil_slash] run function animated_java:dimension_slash/variants/slash2/zzz/13
execute on passengers if entity @s[tag=aj.dimension_slash.bone.moonveil] run function animated_java:dimension_slash/variants/slash2/zzz/14
execute on passengers if entity @s[tag=aj.dimension_slash.bone.left_arm] run function animated_java:dimension_slash/variants/slash2/zzz/15
execute on passengers if entity @s[tag=aj.dimension_slash.bone.head] run function animated_java:dimension_slash/variants/slash2/zzz/16
execute on passengers if entity @s[tag=aj.dimension_slash.bone.body_top] run function animated_java:dimension_slash/variants/slash2/zzz/17
execute on passengers if entity @s[tag=aj.dimension_slash.bone.body] run function animated_java:dimension_slash/variants/slash2/zzz/18
execute on passengers if entity @s[tag=aj.dimension_slash.bone.right_leg2] run function animated_java:dimension_slash/variants/slash2/zzz/19
execute on passengers if entity @s[tag=aj.dimension_slash.bone.right_leg] run function animated_java:dimension_slash/variants/slash2/zzz/20
execute on passengers if entity @s[tag=aj.dimension_slash.bone.left_leg2] run function animated_java:dimension_slash/variants/slash2/zzz/21
execute on passengers if entity @s[tag=aj.dimension_slash.bone.left_leg] run function animated_java:dimension_slash/variants/slash2/zzz/22